cargo-features = ["profile-rustflags"]

[package]
name = "zenix"
version.workspace = true
build = "meta/multiboot_build.rs"

[workspace.package]
version = "0.1.0"

[[bin]]
name = "zenix"
path = "meta/qemu.rs"

[build-dependencies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

[workspace]
resolver = "2"
members = [
	"pre-kernel",
	"kernel",
]

[profile.pre-kernel-debug]
inherits = "release"
debug = true
split-debuginfo = "packed"
