[package]
name = "kernel"
edition = "2021"
version.workspace = true
license.workspace = true

[dependencies]
bootinfo = { workspace = true }
essentials = { workspace = true }
x86_64 = { workspace = true }
path = { workspace = true }
