[package]
name = "pre-kernel"
edition = "2021"
version.workspace = true
license.workspace = true

[dependencies]
x86_64 = { workspace = true }
bootinfo = { workspace = true }
essentials = { workspace = true }
elf = { workspace = true }
